gh-container: error on unknown action
Fail script is action is not valid

diff --git a/gh-container b/gh-container
--- a/gh-container
+++ b/gh-container
@@ -195,4 +195,7 @@ elif [ "${ACTION}" == "versions" ]; then
     list_versions $@
 elif [ "${ACTION}" == "clean" ]; then
     clean $@
+else
+    echo "Error: Unknown action"
+    exit 1
 fi
